/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PricingTierRouteRouteImport } from './routes/pricing-tier/route'
import { Route as ErrorsRouteRouteImport } from './routes/errors/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ClientManagementRouteRouteImport } from './routes/client-management/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ClientManagementIndexRouteImport } from './routes/client-management/index'
import { Route as PricingTierConfigureRouteImport } from './routes/pricing-tier/configure'
import { Route as ErrorsNotFoundRouteImport } from './routes/errors/not-found'
import { Route as ErrorsForbiddenRouteImport } from './routes/errors/forbidden'
import { Route as ClientManagementOnboardingRouteImport } from './routes/client-management/onboarding'
import { Route as ClientManagementUpdateIdRouteImport } from './routes/client-management/update/$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingTierRouteRoute = PricingTierRouteRouteImport.update({
  id: '/pricing-tier',
  path: '/pricing-tier',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRouteRoute = ErrorsRouteRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientManagementRouteRoute = ClientManagementRouteRouteImport.update({
  id: '/client-management',
  path: '/client-management',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ClientManagementIndexRoute = ClientManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientManagementRouteRoute,
} as any)
const PricingTierConfigureRoute = PricingTierConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => PricingTierRouteRoute,
} as any)
const ErrorsNotFoundRoute = ErrorsNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => ErrorsRouteRoute,
} as any)
const ErrorsForbiddenRoute = ErrorsForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => ErrorsRouteRoute,
} as any)
const ClientManagementOnboardingRoute =
  ClientManagementOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => ClientManagementRouteRoute,
  } as any)
const ClientManagementUpdateIdRoute =
  ClientManagementUpdateIdRouteImport.update({
    id: '/update/$id',
    path: '/update/$id',
    getParentRoute: () => ClientManagementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-management': typeof ClientManagementRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/errors': typeof ErrorsRouteRouteWithChildren
  '/pricing-tier': typeof PricingTierRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/client-management/onboarding': typeof ClientManagementOnboardingRoute
  '/errors/forbidden': typeof ErrorsForbiddenRoute
  '/errors/not-found': typeof ErrorsNotFoundRoute
  '/pricing-tier/configure': typeof PricingTierConfigureRoute
  '/client-management/': typeof ClientManagementIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/client-management/update/$id': typeof ClientManagementUpdateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/errors': typeof ErrorsRouteRouteWithChildren
  '/pricing-tier': typeof PricingTierRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/client-management/onboarding': typeof ClientManagementOnboardingRoute
  '/errors/forbidden': typeof ErrorsForbiddenRoute
  '/errors/not-found': typeof ErrorsNotFoundRoute
  '/pricing-tier/configure': typeof PricingTierConfigureRoute
  '/client-management': typeof ClientManagementIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/client-management/update/$id': typeof ClientManagementUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client-management': typeof ClientManagementRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/errors': typeof ErrorsRouteRouteWithChildren
  '/pricing-tier': typeof PricingTierRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/client-management/onboarding': typeof ClientManagementOnboardingRoute
  '/errors/forbidden': typeof ErrorsForbiddenRoute
  '/errors/not-found': typeof ErrorsNotFoundRoute
  '/pricing-tier/configure': typeof PricingTierConfigureRoute
  '/client-management/': typeof ClientManagementIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/client-management/update/$id': typeof ClientManagementUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client-management'
    | '/dashboard'
    | '/errors'
    | '/pricing-tier'
    | '/sign-in'
    | '/client-management/onboarding'
    | '/errors/forbidden'
    | '/errors/not-found'
    | '/pricing-tier/configure'
    | '/client-management/'
    | '/dashboard/'
    | '/client-management/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/errors'
    | '/pricing-tier'
    | '/sign-in'
    | '/client-management/onboarding'
    | '/errors/forbidden'
    | '/errors/not-found'
    | '/pricing-tier/configure'
    | '/client-management'
    | '/dashboard'
    | '/client-management/update/$id'
  id:
    | '__root__'
    | '/'
    | '/client-management'
    | '/dashboard'
    | '/errors'
    | '/pricing-tier'
    | '/sign-in'
    | '/client-management/onboarding'
    | '/errors/forbidden'
    | '/errors/not-found'
    | '/pricing-tier/configure'
    | '/client-management/'
    | '/dashboard/'
    | '/client-management/update/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientManagementRouteRoute: typeof ClientManagementRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ErrorsRouteRoute: typeof ErrorsRouteRouteWithChildren
  PricingTierRouteRoute: typeof PricingTierRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-tier': {
      id: '/pricing-tier'
      path: '/pricing-tier'
      fullPath: '/pricing-tier'
      preLoaderRoute: typeof PricingTierRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-management': {
      id: '/client-management'
      path: '/client-management'
      fullPath: '/client-management'
      preLoaderRoute: typeof ClientManagementRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/client-management/': {
      id: '/client-management/'
      path: '/'
      fullPath: '/client-management/'
      preLoaderRoute: typeof ClientManagementIndexRouteImport
      parentRoute: typeof ClientManagementRouteRoute
    }
    '/pricing-tier/configure': {
      id: '/pricing-tier/configure'
      path: '/configure'
      fullPath: '/pricing-tier/configure'
      preLoaderRoute: typeof PricingTierConfigureRouteImport
      parentRoute: typeof PricingTierRouteRoute
    }
    '/errors/not-found': {
      id: '/errors/not-found'
      path: '/not-found'
      fullPath: '/errors/not-found'
      preLoaderRoute: typeof ErrorsNotFoundRouteImport
      parentRoute: typeof ErrorsRouteRoute
    }
    '/errors/forbidden': {
      id: '/errors/forbidden'
      path: '/forbidden'
      fullPath: '/errors/forbidden'
      preLoaderRoute: typeof ErrorsForbiddenRouteImport
      parentRoute: typeof ErrorsRouteRoute
    }
    '/client-management/onboarding': {
      id: '/client-management/onboarding'
      path: '/onboarding'
      fullPath: '/client-management/onboarding'
      preLoaderRoute: typeof ClientManagementOnboardingRouteImport
      parentRoute: typeof ClientManagementRouteRoute
    }
    '/client-management/update/$id': {
      id: '/client-management/update/$id'
      path: '/update/$id'
      fullPath: '/client-management/update/$id'
      preLoaderRoute: typeof ClientManagementUpdateIdRouteImport
      parentRoute: typeof ClientManagementRouteRoute
    }
  }
}

interface ClientManagementRouteRouteChildren {
  ClientManagementOnboardingRoute: typeof ClientManagementOnboardingRoute
  ClientManagementIndexRoute: typeof ClientManagementIndexRoute
  ClientManagementUpdateIdRoute: typeof ClientManagementUpdateIdRoute
}

const ClientManagementRouteRouteChildren: ClientManagementRouteRouteChildren = {
  ClientManagementOnboardingRoute: ClientManagementOnboardingRoute,
  ClientManagementIndexRoute: ClientManagementIndexRoute,
  ClientManagementUpdateIdRoute: ClientManagementUpdateIdRoute,
}

const ClientManagementRouteRouteWithChildren =
  ClientManagementRouteRoute._addFileChildren(
    ClientManagementRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ErrorsRouteRouteChildren {
  ErrorsForbiddenRoute: typeof ErrorsForbiddenRoute
  ErrorsNotFoundRoute: typeof ErrorsNotFoundRoute
}

const ErrorsRouteRouteChildren: ErrorsRouteRouteChildren = {
  ErrorsForbiddenRoute: ErrorsForbiddenRoute,
  ErrorsNotFoundRoute: ErrorsNotFoundRoute,
}

const ErrorsRouteRouteWithChildren = ErrorsRouteRoute._addFileChildren(
  ErrorsRouteRouteChildren,
)

interface PricingTierRouteRouteChildren {
  PricingTierConfigureRoute: typeof PricingTierConfigureRoute
}

const PricingTierRouteRouteChildren: PricingTierRouteRouteChildren = {
  PricingTierConfigureRoute: PricingTierConfigureRoute,
}

const PricingTierRouteRouteWithChildren =
  PricingTierRouteRoute._addFileChildren(PricingTierRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientManagementRouteRoute: ClientManagementRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ErrorsRouteRoute: ErrorsRouteRouteWithChildren,
  PricingTierRouteRoute: PricingTierRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
